### ISSUE TITLE
No Database Or SQL supplied with project

### ISSUE THREAD

**Issue by narendrasharma** [LukaszFilipowski/seatBooking#1]
I was unable to run this application as there is no database f ile supllied with the downloaded zip.
i wanted to fork the script to get to this to another level .
Developers please supply this file so others can use it or fork it.
thank you guys
awesome work done by you but pay attention to this issue.
Happy Coding :)

**Comment by LukaszFilipowski** [comment]
There are migrations. 

https://laravel.com/docs/5.4/migrations
